services:
  funmasters:
    image: funmasters
    build:
      context: .
      dockerfile: FunMasters/FunMasters/Dockerfile

  funmasters.client:
    image: funmasters.client
    build:
      context: .
      dockerfile: FunMasters/FunMasters.Client/Dockerfile

